name: Churn_env CI/CD Pipeline

on:
  push:
    branches: [ main ]

jobs:
  build-test-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.10.19"

    - name: Install dependencies
      run: |
        pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run ML pipeline
      run: |
        python pipelines/1_ingest.py
        python pipelines/2_preprocess.py
        python pipelines/3_train.py
        python pipelines/4_predict.py
        python analytics/churn_kpis.py
        python segmentation/customer_intelligence.py

    - name: Build Docker image
      run: docker build -t churn-env-app .

    - name: Log in to DockerHub
      if: secrets.DOCKER_USERNAME && secrets.DOCKER_PASSWORD
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Push Docker image
      if: secrets.DOCKER_USERNAME && secrets.DOCKER_PASSWORD
      run: |
        docker tag churn-env-app:latest ${{ secrets.DOCKER_USERNAME }}/churn-env-app:latest
        docker push ${{ secrets.DOCKER_USERNAME }}/churn-env-app:latest

    - name: Success
      run: echo "âœ… CI/CD pipeline completed successfully!"